---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: corp-eks-cluster
  region: us-east-1
  version: "1.21"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small

cloudWatch:
  clusterLogging:
    enableTypes: 
      - "controllerManager"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: dynamodb-read-only
    attachPolicyARNs:
    - arn:aws:iam::648106300517:policy/eks-directory-service
