apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-service
  labels:
    app: directory-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directory-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: directory-service
    spec:
      serviceAccountName: dynamodb-read-only
      containers:
      - image: 648106300517.dkr.ecr.us-east-1.amazonaws.com/corpidirectory:latest
        imagePullPolicy: Always
        name: directory-service
        ports:
        - containerPort: 80
          protocol: TCP
